# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookwave < Formula
  desc "Hookwave CLI — reliable webhook infrastructure for AI agents"
  homepage "https://hookwave.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Hookwave/Hookwave/releases/download/v0.1.0/hookwave_0.1.0_darwin_x86_64.tar.gz"
      sha256 "638f087158cfe6e52012616fc15d545d38f9155dc651b82661cc069c6fb105f1"

      define_method(:install) do
        bin.install "hookwave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Hookwave/Hookwave/releases/download/v0.1.0/hookwave_0.1.0_darwin_arm64.tar.gz"
      sha256 "6004779ac44a6f163953894ae69262263e1caaa93da5792797ccfd35763f822c"

      define_method(:install) do
        bin.install "hookwave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hookwave/Hookwave/releases/download/v0.1.0/hookwave_0.1.0_linux_x86_64.tar.gz"
      sha256 "af64ca3c36ed01af14e94b507676e2538bc4fd32a9f98e4cdbb8fb97fb716c9e"
      define_method(:install) do
        bin.install "hookwave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hookwave/Hookwave/releases/download/v0.1.0/hookwave_0.1.0_linux_arm64.tar.gz"
      sha256 "1eb7a914b665942d447ebb45a04de365d0310bfa8380446f0df4d39abfafad39"
      define_method(:install) do
        bin.install "hookwave"
      end
    end
  end

  test do
    system "#{bin}/hookwave --version"
  end
end
